version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run

jobs:
  hello-job:
    executor: node # use the `node` executor defined above
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job